AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Function
Resources:
  PhotoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: HW2LF2
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./LF2_searchphotos
      Description: "Lambda function 2 for searching photos"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::742929579116:role/service-role/search-photos-role-0e48fs49"