AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda Function
Resources:
  PhotoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: HW2LF1
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./LF1_indexphotos
      Description: "Lambda function 1 for indexing photos"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::742929579116:role/service-role/index-photos-role-v0yc0s4e"
